# Copyright 2019 Manna Harbour
# https://github.com/manna-harbour/miryoku

MIRYOKU_ALPHAS=QWERTY
MIRYOKU_EXTRA=COLEMAKDH
MIRYOKU_TAP=QWERTY
MIRYOKU_NAV=VI
# MIRYOKU_CLIPBOARD=FUN
# MIRYOKU_LAYERS=FLIP
